[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npx prisma db push && npx tsx src/prisma/seed.ts && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
